### ISSUE TITLE
When linux support will be added?

### ISSUE THREAD

**Issue by toprak** [engMaher/LLG-MP#5]
I hope you will add it soon.

**Comment by engMaher** [comment]
a new beta release will be published soon with the following features/bug fixes with linux support included : 

![image](https://user-images.githubusercontent.com/9812431/79702136-d8183780-82a2-11ea-9b1e-431522a9f57d.png)

so ,  stay tuned ;) 

> I hope you will add it soon.

**Comment by cartals** [comment]
Oh thanks!

**Comment by cartals** [comment]
I'd like to add Turkish localization when the Linux version will be out.

**Comment by engMaher** [comment]
Added Linux support & all language support
