### ISSUE TITLE
It can't see subtitles which is come with video.

### ISSUE THREAD

**Issue by toprak** [engMaher/LLG-MP#6]
Hi, I've some animes on my pc which are softsub, I tried on my windows-laptop and it can't detect it, I wonder it happened because of they are .ass?

**Comment by engMaher** [comment]
Currently the supported subtitles formats are (.vtt & .srt) , the SubStation Alpha formats (.ass & .ssa) are unfortunately not supported currently , i've labled your thread as a feature request to be added in the queue of the solution development [requested features section]

**Comment by engMaher** [comment]
Added support for all popular subtitles formats (.srt,.vtt,.ass,.ssa,.sub,.sbv,.smi,.lrc,.json)

**Comment by engMaher** [comment]
Added support for all popular subtitles formats (.srt,.vtt,.ass,.ssa,.sub,.sbv,.smi,.lrc,.json)
